### ISSUE TITLE
Add loopback addresses

### ISSUE THREAD

**Issue by crossett** [stealthybox/multicluster-gitops#1]
I enjoyed your presentation at KubeCon.  You might want to add the following to your README.md so that the `kind/setup.sh` script would work.

```shell
sudo ifconfig lo0 alias 127.0.0.2
sudo ifconfig lo0 alias 127.0.0.3
```

Thanks,
Jonathan

**Comment by crossett** [comment]
Actually, this doesn't seem to be the fix.  What was done to make 127.0.0.2 and 127.0.0.3 available? (I'm using Docker Desktop for Mac).

Thanks,
Jonathan

**Comment by stealthybox** [comment]
using individual loopback addresses
- works on linux
- is ignored on docker-for-windows(wsl2)
- breaks host->controlplane communication on docker-for-mac

Sorry that you ran into this and thanks so much for the dm and issue :)

I'm going to comment these out since the individual loopbacks and ports are just a nice-to-have.
They're not needed for the demo.

**Comment by stealthybox** [comment]
This is probably related
https://github.com/docker/for-mac/issues/4607

**Comment by stealthybox** [comment]
^ Commented out the loopbacks and port-forwards.
This shouldn't be a problem for mac users anymore ⛵
